[build]
  # Build command for React app
  command = "npm run build"
  # Output directory after build
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# API Redirects for Netlify Functions

# KV Storage endpoints
[[redirects]]
  from = "/api/kv/upsert"
  to = "/.netlify/functions/kv-upsert"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/kv/get"
  to = "/.netlify/functions/kv-get"
  status = 200

[[redirects]]
  from = "/api/kv/list"
  to = "/.netlify/functions/kv-list"
  status = 200

# Photo upload endpoint
[[redirects]]
  from = "/api/photo-upload"
  to = "/.netlify/functions/photo-upload"
  status = 200

# Log writing endpoint
[[redirects]]
  from = "/api/write-log"
  to = "/.netlify/functions/write-log"
  status = 200
  force = true

# Supabase test endpoint
[[redirects]]
  from = "/api/test-supabase"
  to = "/.netlify/functions/test-supabase"
  status = 200

# Settings endpoints
[[redirects]]
  from = "/api/settings/*"
  to = "/.netlify/functions/settings-get/:splat"
  status = 200
  conditions = {method = ["GET"]}
  force = true

[[redirects]]
  from = "/api/settings/*"
  to = "/.netlify/functions/settings-set/:splat"
  status = 200
  conditions = {method = ["POST"]}
  force = true

# Progress endpoints
[[redirects]]
  from = "/api/progress/*"
  to = "/.netlify/functions/progress-get/:splat"
  status = 200
  conditions = {method = ["GET"]}
  force = true

[[redirects]]
  from = "/api/progress/*"
  to = "/.netlify/functions/progress-set/:splat"
  status = 200
  conditions = {method = ["POST"]}
  force = true

# Sponsors endpoint
[[redirects]]
  from = "/api/sponsors"
  to = "/.netlify/functions/sponsors-get"
  status = 200
  conditions = {method = ["POST"]}
  force = true

# Leaderboard endpoint
[[redirects]]
  from = "/api/leaderboard/*"
  to = "/.netlify/functions/leaderboard-get/:splat"
  status = 200
  conditions = {method = ["GET"]}
  force = true

# Team endpoints
[[redirects]]
  from = "/api/team-verify"
  to = "/.netlify/functions/team-verify"
  status = 200
  conditions = {method = ["POST"]}
  force = true

[[redirects]]
  from = "/api/team-current"
  to = "/.netlify/functions/team-current"
  status = 200
  conditions = {method = ["GET"]}
  force = true

[[redirects]]
  from = "/api/team-setup"
  to = "/.netlify/functions/team-setup"
  status = 200
  conditions = {method = ["POST"]}
  force = true

# Legacy state endpoints (can be removed if not used)
[[redirects]]
  from = "/api/state-get/*"
  to = "/.netlify/functions/state-get/:splat"
  status = 200

[[redirects]]
  from = "/api/state-set"
  to = "/.netlify/functions/state-set"
  status = 200

[[redirects]]
  from = "/api/state-delete/*"
  to = "/.netlify/functions/state-delete/:splat"
  status = 200

[[redirects]]
  from = "/api/state-list"
  to = "/.netlify/functions/state-list"
  status = 200

[[redirects]]
  from = "/api/state-clear"
  to = "/.netlify/functions/state-clear"
  status = 200

# Favicon redirect
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.svg"
  status = 200

# SPA fallback - serve index.html for all non-API routes
# IMPORTANT: This must be LAST to avoid intercepting API calls
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Netlify Blobs configuration
[[blobs]]
name = "kv"

[[blobs]]
name = "hunt-data"

# Local development settings

# Local development settings to proxy to Vite dev server
[dev]
  command = "npm run dev"       # start the Vite UI for Netlify Dev
  port = 8888                    # Netlify Dev UI port
  targetPort = 5173              # Vite dev server port
  publish = "."                 # serve from project root in dev
  autoLaunch = false

# Environment variables (set these in Netlify dashboard)
# NETLIFY_BLOBS_STORE_NAME = "vail-hunt-state"