[build]
  # Build command for React app
  command = "npm run build"
  # Output directory after build
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect API calls to functions
[[redirects]]
  from = "/api/state-get/*"
  to = "/.netlify/functions/state-get/:splat"
  status = 200

[[redirects]]
  from = "/api/state-set"
  to = "/.netlify/functions/state-set"
  status = 200

[[redirects]]
  from = "/api/state-delete/*"
  to = "/.netlify/functions/state-delete/:splat"
  status = 200

[[redirects]]
  from = "/api/state-list"
  to = "/.netlify/functions/state-list"
  status = 200

[[redirects]]
  from = "/api/state-clear"
  to = "/.netlify/functions/state-clear"
  status = 200

# SPA fallback - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Netlify Blobs configuration
[[blobs]]
name = "kv"

[[blobs]]
name = "hunt-data"

# Netlify Functions redirects for the new KV endpoints
[[redirects]]
  from = "/api/kv/upsert"
  to = "/.netlify/functions/kv-upsert"
  status = 200

[[redirects]]
  from = "/api/kv/get"
  to = "/.netlify/functions/kv-get"
  status = 200

[[redirects]]
  from = "/api/kv/list"
  to = "/.netlify/functions/kv-list"
  status = 200

[[redirects]]
  from = "/api/photo-upload"
  to = "/.netlify/functions/photo-upload"
  status = 200

# Settings endpoints - GET requests
[[redirects]]
  from = "/api/settings/*"
  to = "/.netlify/functions/settings-get/:splat"
  status = 200
  conditions = {method = ["GET"]}

# Settings endpoints - POST requests for saving
[[redirects]]
  from = "/api/settings/*"
  to = "/.netlify/functions/settings-set/:splat"
  status = 200
  conditions = {method = ["POST"]}

# Progress endpoints - GET requests
[[redirects]]
  from = "/api/progress/*"
  to = "/.netlify/functions/progress-get/:splat"
  status = 200
  conditions = {method = ["GET"]}

# Progress endpoints - POST requests for saving
[[redirects]]
  from = "/api/progress/*"
  to = "/.netlify/functions/progress-set/:splat"
  status = 200
  conditions = {method = ["POST"]}

# Local development settings to proxy to Vite dev server
[dev]
  command = "npm run dev"       # start the Vite UI for Netlify Dev
  port = 8888                    # Netlify Dev UI port
  targetPort = 5173              # Vite dev server port
  publish = "."                 # serve from project root in dev
  autoLaunch = false

# Map favicon.ico to the existing SVG during local dev and Netlify preview
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.svg"
  status = 200

# Environment variables (set these in Netlify dashboard)
# NETLIFY_BLOBS_STORE_NAME = "vail-hunt-state"